Fixed some Unit Tests [Treatment + Medicine]
Ducks-Net/SiDiez pull request #49
Opened 2022-12-02 15:41 UTC by anamariaghiorghiu

2022-12-04 09:31 UTC, OpariucRares requested changes
don't add the DucksNet.db, DucksNet.db-shm, DucksNet.db-wal. remove for the push, but keet it local

2022-12-04 09:31 UTC, OpariucRares commented on src/DucksNet.API/Controllers/TreatmentController.cs
> +    //private readonly IRepository<Medicine> _medicineRepository;
mark as a TODO (abbreviation of your name)

2022-12-04 09:31 UTC, OpariucRares commented on src/DucksNet.Domain/Model/Medicine.cs
> +using System.Net;
does it need?

2022-12-04 09:31 UTC, OpariucRares commented on tests/DucksNet.IntegrationTests/TreatmentControllerTests.cs
> +//namespace DucksNet.IntegrationTests;
why is it commented? make at least one test

2022-12-04 09:31 UTC, OpariucRares commented on tests/DucksNet.UnitTests/TreatmentTests.cs
> +    //}
same here. At least make the treatment domain 100%

2022-12-05 00:16 UTC, OpariucRares requested changes
make for all the ifs

2022-12-05 00:16 UTC, OpariucRares commented on src/DucksNet.Domain/Model/Medicine.cs
> +        else if (string.IsNullOrWhiteSpace(name))
you can remove the ifs; let alone else

2022-12-05 05:05 UTC, Al-Andrew approved these changes
All in all seems fine. But please uncomment out the removing of treatments fro the database when testing.

2022-12-05 05:05 UTC, Al-Andrew commented on src/DucksNet.Domain/Model/Medicine.cs
> +        }
the if and elif overlap on price = 0 here

2022-12-05 05:05 UTC, Al-Andrew commented on tests/DucksNet.IntegrationTests/BaseIntegrationTests.cs
> +        //context.RemoveRange(context.Treatments);
Why should we not clean out the Treatments?

2022-12-05 05:05 UTC, Al-Andrew commented on tests/DucksNet.IntegrationTests/MedicineControllerTests.cs
> +    //}
Why is this test commented out?

2022-12-05 08:10 UTC, OpariucRares approved these changes

2022-12-05 08:16 UTC, merged