CRUD for Pet and User (not fully completed)
Ducks-Net/SiDiez pull request #57
Opened 2022-12-04 22:53 UTC by adinaned

2022-12-04 23:32 UTC, OpariucRares requested changes
look at comments

2022-12-04 23:32 UTC, OpariucRares commented on src/DucksNet.WebUI/Pages/Models/CreatePetModel.cs
> +    public string? PetId { get; set; }
you do not need this

2022-12-04 23:32 UTC, OpariucRares commented on src/DucksNet.WebUI/Pages/Models/CreateUserModel.cs
> +
same here

2022-12-05 04:52 UTC, Al-Andrew approved these changes
Seems good enough

2022-12-05 04:52 UTC, Al-Andrew commented on src/DucksNet.WebUI/Pages/Models/UpdatePetModel.cs
> +    public string? Name { get; set; }
What happens If I pass null into any of the ones not marked required?

2022-12-05 04:52 UTC, Al-Andrew commented on src/DucksNet.WebUI/Pages/Models/UpdateUserModel.cs
> +    public string? Password { get; set; }
What happens if I pass null into any of the ones not marked Required?

2022-12-05 04:52 UTC, Al-Andrew commented on src/DucksNet.WebUI/Pages/Services/UserDataServices.cs
> +    }
Is this function needed/used?

2022-12-05 08:01 UTC, OpariucRares approved these changes
good

2022-12-05 08:10 UTC, merged